services:
    minio:
        restart: always
        image: minio/minio:latest
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:9001/"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - ./minio_data:/data

    mc:
        image: minio/mc:latest
        depends_on:
            minio:
                condition: service_healthy
        container_name: mc
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            /usr/bin/mc mb minio/models;
            exit 0;
            "

    triton:
        image: nvcr.io/nvidia/tritonserver:25.04-py3
        container_name: triton
        depends_on:
            mc:
                condition: service_completed_successfully
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://127.0.0.1:8002/" ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "8100:8000"
            - "8101:8001"
            - "8102:8002"
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        entrypoint: "tritonserver --model-repository=s3://minio:9000/models --model-control-mode=poll --repository-poll-secs 60"

    server:
        build: .
        depends_on:
            triton:
                condition: service_healthy
        entrypoint: uvicorn app:app --port 8090 --host 0.0.0.0
        container_name: server
        ports:
            - 8090:8090
